### ISSUE TITLE
Please update the sailor version

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/aws-sns-component#2]
Sailor version is too old, cannot be deployed into elastic.io

**Comment by zubairov** [comment]
@khanzadyan fixed

**Comment by khanzadyan** [comment]
Thanks @zubairov I will start deploring this into the tenants. Should I close this?

**Comment by khanzadyan** [comment]
Deployment confirmed.

**Comment by stas-fomenko** [comment]
tested
